### PR TITLE
Write some docs

### PR DESCRIPTION
**Pull request by mattleibow**

### CODE REVIEW

**Comment by lobrien** [comment]
Docs Build status updates of commit _[e599d10](https://github.com/mono/SkiaSharp-API-docs/pull/11/commits/e599d10808f32e02d60bb3dc75afea638f96c72d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[SkiaSharpAPI/HarfBuzzSharp/Blob.xml](https://github.com/mono/SkiaSharp-API-docs/blob/updates/SkiaSharpAPI/HarfBuzzSharp/Blob.xml) | :white_check_mark:Succeeded | |
[SkiaSharpAPI/HarfBuzzSharp/Buffer.xml](https://github.com/mono/SkiaSharp-API-docs/blob/updates/SkiaSharpAPI/HarfBuzzSharp/Buffer.xml) | :white_check_mark:Succeeded | |
[SkiaSharpAPI/HarfBuzzSharp/FontExtentsDelegate.xml](https://github.com/mono/SkiaSharp-API-docs/blob/updates/SkiaSharpAPI/HarfBuzzSharp/FontExtentsDelegate.xml) | :white_check_mark:Succeeded | |
[SkiaSharpAPI/HarfBuzzSharp/GlyphAdvanceDelegate.xml](https://github.com/mono/SkiaSharp-API-docs/blob/updates/SkiaSharpAPI/HarfBuzzSharp/GlyphAdvanceDelegate.xml) | :white_check_mark:Succeeded | |
[SkiaSharpAPI/SkiaSharp/SKBitmap.xml](https://github.com/mono/SkiaSharp-API-docs/blob/updates/SkiaSharpAPI/SkiaSharp/SKBitmap.xml) | :white_check_mark:Succeeded | |
[SkiaSharpAPI/SkiaSharp/SKData.xml](https://github.com/mono/SkiaSharp-API-docs/blob/updates/SkiaSharpAPI/SkiaSharp/SKData.xml) | :white_check_mark:Succeeded | |
[SkiaSharpAPI/SkiaSharp/SKPixmap.xml](https://github.com/mono/SkiaSharp-API-docs/blob/updates/SkiaSharpAPI/SkiaSharp/SKPixmap.xml) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C6%5C28%5Cd74d06e1-35fd-4f5e-5721-3c1847329f0d%5CPullRequest%5C201906280125096603-11%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=4khnazNt869ZfZZVEdM3RI22T7yS1EVlRTtzdRlH4GM%3D&st=2019-06-28T01%3A22%3A07Z&se=2019-07-29T01%3A27%3A07Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by lobrien** [comment]
Docs Build status updates of commit _[f4efaa3](https://github.com/mono/SkiaSharp-API-docs/pull/11/commits/f4efaa3825956b33d2180a1b0b34a93d6635a915)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[SkiaSharpAPI/FrameworksIndex/harfbuzzsharp-2.3.1.xml](https://github.com/mono/SkiaSharp-API-docs/blob/updates/SkiaSharpAPI/FrameworksIndex/harfbuzzsharp-2.3.1.xml) | :white_check_mark:Succeeded | |
[SkiaSharpAPI/FrameworksIndex/harfbuzzsharp-2.5.2.xml](https://github.com/mono/SkiaSharp-API-docs/blob/updates/SkiaSharpAPI/FrameworksIndex/harfbuzzsharp-2.5.2.xml) | :white_check_mark:Succeeded | |
[SkiaSharpAPI/HarfBuzzSharp/Blob.xml](https://github.com/mono/SkiaSharp-API-docs/blob/updates/SkiaSharpAPI/HarfBuzzSharp/Blob.xml) | :white_check_mark:Succeeded | |
[SkiaSharpAPI/HarfBuzzSharp/Buffer.xml](https://github.com/mono/SkiaSharp-API-docs/blob/updates/SkiaSharpAPI/HarfBuzzSharp/Buffer.xml) | :white_check_mark:Succeeded | |
[SkiaSharpAPI/HarfBuzzSharp/BufferFlags.xml](https://github.com/mono/SkiaSharp-API-docs/blob/updates/SkiaSharpAPI/HarfBuzzSharp/BufferFlags.xml) | :white_check_mark:Succeeded | |
[SkiaSharpAPI/HarfBuzzSharp/Face.xml](https://github.com/mono/SkiaSharp-API-docs/blob/updates/SkiaSharpAPI/HarfBuzzSharp/Face.xml) | :white_check_mark:Succeeded | |
[SkiaSharpAPI/HarfBuzzSharp/Feature.xml](https://github.com/mono/SkiaSharp-API-docs/blob/updates/SkiaSharpAPI/HarfBuzzSharp/Feature.xml) | :white_check_mark:Succeeded | |
[SkiaSharpAPI/HarfBuzzSharp/Flags.xml](https://github.com/mono/SkiaSharp-API-docs/blob/updates/SkiaSharpAPI/HarfBuzzSharp/Flags.xml) | :white_check_mark:Succeeded | |
[SkiaSharpAPI/HarfBuzzSharp/Font.xml](https://github.com/mono/SkiaSharp-API-docs/blob/updates/SkiaSharpAPI/HarfBuzzSharp/Font.xml) | :white_check_mark:Succeeded | |
[SkiaSharpAPI/HarfBuzzSharp/FontExtentsDelegate.xml](https://github.com/mono/SkiaSharp-API-docs/blob/updates/SkiaSharpAPI/HarfBuzzSharp/FontExtentsDelegate.xml) | :white_check_mark:Succeeded | |
[SkiaSharpAPI/HarfBuzzSharp/GlyphAdvanceDelegate.xml](https://github.com/mono/SkiaSharp-API-docs/blob/updates/SkiaSharpAPI/HarfBuzzSharp/GlyphAdvanceDelegate.xml) | :white_check_mark:Succeeded | |
[SkiaSharpAPI/SkiaSharp/SKBitmap.xml](https://github.com/mono/SkiaSharp-API-docs/blob/updates/SkiaSharpAPI/SkiaSharp/SKBitmap.xml) | :white_check_mark:Succeeded | |
[SkiaSharpAPI/SkiaSharp/SKData.xml](https://github.com/mono/SkiaSharp-API-docs/blob/updates/SkiaSharpAPI/SkiaSharp/SKData.xml) | :white_check_mark:Succeeded | |
[SkiaSharpAPI/SkiaSharp/SKPixmap.xml](https://github.com/mono/SkiaSharp-API-docs/blob/updates/SkiaSharpAPI/SkiaSharp/SKPixmap.xml) | :white_check_mark:Succeeded | |
[SkiaSharpAPI/index.xml](https://github.com/mono/SkiaSharp-API-docs/blob/updates/SkiaSharpAPI/index.xml) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C6%5C28%5Cd74d06e1-35fd-4f5e-5721-3c1847329f0d%5CPullRequest%5C201906280156485752-11%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=N0bQ3LfxD%2BDrwLs2pO03RlTFXV7y2nl3XS%2Btb%2Bp9KZw%3D&st=2019-06-28T01%3A53%3A52Z&se=2019-07-29T01%3A58%3A52Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by lobrien** [comment]
Docs Build status updates of commit _[4f8138f](https://github.com/mono/SkiaSharp-API-docs/pull/11/commits/4f8138f1b0c33ac2ae482399df890af4437b858e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[SkiaSharpAPI/FrameworksIndex/harfbuzzsharp-2.3.1.xml](https://github.com/mono/SkiaSharp-API-docs/blob/updates/SkiaSharpAPI/FrameworksIndex/harfbuzzsharp-2.3.1.xml) | :white_check_mark:Succeeded | |
[SkiaSharpAPI/FrameworksIndex/harfbuzzsharp-2.5.2.xml](https://github.com/mono/SkiaSharp-API-docs/blob/updates/SkiaSharpAPI/FrameworksIndex/harfbuzzsharp-2.5.2.xml) | :white_check_mark:Succeeded | |
[SkiaSharpAPI/HarfBuzzSharp/Blob.xml](https://github.com/mono/SkiaSharp-API-docs/blob/updates/SkiaSharpAPI/HarfBuzzSharp/Blob.xml) | :white_check_mark:Succeeded | |
[SkiaSharpAPI/HarfBuzzSharp/Buffer.xml](https://github.com/mono/SkiaSharp-API-docs/blob/updates/SkiaSharpAPI/HarfBuzzSharp/Buffer.xml) | :white_check_mark:Succeeded | |
[SkiaSharpAPI/HarfBuzzSharp/BufferFlags.xml](https://github.com/mono/SkiaSharp-API-docs/blob/updates/SkiaSharpAPI/HarfBuzzSharp/BufferFlags.xml) | :white_check_mark:Succeeded | |
[SkiaSharpAPI/HarfBuzzSharp/Face.xml](https://github.com/mono/SkiaSharp-API-docs/blob/updates/SkiaSharpAPI/HarfBuzzSharp/Face.xml) | :white_check_mark:Succeeded | |
[SkiaSharpAPI/HarfBuzzSharp/Feature.xml](https://github.com/mono/SkiaSharp-API-docs/blob/updates/SkiaSharpAPI/HarfBuzzSharp/Feature.xml) | :white_check_mark:Succeeded | |
[SkiaSharpAPI/HarfBuzzSharp/Flags.xml](https://github.com/mono/SkiaSharp-API-docs/blob/updates/SkiaSharpAPI/HarfBuzzSharp/Flags.xml) | :white_check_mark:Succeeded | |
[SkiaSharpAPI/HarfBuzzSharp/Font.xml](https://github.com/mono/SkiaSharp-API-docs/blob/updates/SkiaSharpAPI/HarfBuzzSharp/Font.xml) | :white_check_mark:Succeeded | |
[SkiaSharpAPI/HarfBuzzSharp/FontExtentsDelegate.xml](https://github.com/mono/SkiaSharp-API-docs/blob/updates/SkiaSharpAPI/HarfBuzzSharp/FontExtentsDelegate.xml) | :white_check_mark:Succeeded | |
[SkiaSharpAPI/HarfBuzzSharp/GlyphAdvanceDelegate.xml](https://github.com/mono/SkiaSharp-API-docs/blob/updates/SkiaSharpAPI/HarfBuzzSharp/GlyphAdvanceDelegate.xml) | :white_check_mark:Succeeded | |
[SkiaSharpAPI/SkiaSharp/SKBitmap.xml](https://github.com/mono/SkiaSharp-API-docs/blob/updates/SkiaSharpAPI/SkiaSharp/SKBitmap.xml) | :white_check_mark:Succeeded | |
[SkiaSharpAPI/SkiaSharp/SKData.xml](https://github.com/mono/SkiaSharp-API-docs/blob/updates/SkiaSharpAPI/SkiaSharp/SKData.xml) | :white_check_mark:Succeeded | |
[SkiaSharpAPI/SkiaSharp/SKPixmap.xml](https://github.com/mono/SkiaSharp-API-docs/blob/updates/SkiaSharpAPI/SkiaSharp/SKPixmap.xml) | :white_check_mark:Succeeded | |
[SkiaSharpAPI/index.xml](https://github.com/mono/SkiaSharp-API-docs/blob/updates/SkiaSharpAPI/index.xml) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C6%5C28%5Cd74d06e1-35fd-4f5e-5721-3c1847329f0d%5CPullRequest%5C201906280200184363-11%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=3DvfdESGBLFbGCtcvEpsQfwq3bfgpj%2Fv%2BOgNFSyBVWU%3D&st=2019-06-28T01%3A57%3A19Z&se=2019-07-29T02%3A02%3A19Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by lobrien** [comment]
Docs Build status updates of commit _[a9f6a2b](https://github.com/mono/SkiaSharp-API-docs/pull/11/commits/a9f6a2b294cd4027bd82fbcacb9960b852544584)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[SkiaSharpAPI/FrameworksIndex/harfbuzzsharp-2.3.1.xml](https://github.com/mono/SkiaSharp-API-docs/blob/updates/SkiaSharpAPI/FrameworksIndex/harfbuzzsharp-2.3.1.xml) | :white_check_mark:Succeeded | |
[SkiaSharpAPI/FrameworksIndex/harfbuzzsharp-2.5.2.xml](https://github.com/mono/SkiaSharp-API-docs/blob/updates/SkiaSharpAPI/FrameworksIndex/harfbuzzsharp-2.5.2.xml) | :white_check_mark:Succeeded | |
[SkiaSharpAPI/HarfBuzzSharp/Blob.xml](https://github.com/mono/SkiaSharp-API-docs/blob/updates/SkiaSharpAPI/HarfBuzzSharp/Blob.xml) | :white_check_mark:Succeeded | |
[SkiaSharpAPI/HarfBuzzSharp/Buffer.xml](https://github.com/mono/SkiaSharp-API-docs/blob/updates/SkiaSharpAPI/HarfBuzzSharp/Buffer.xml) | :white_check_mark:Succeeded | |
[SkiaSharpAPI/HarfBuzzSharp/BufferFlags.xml](https://github.com/mono/SkiaSharp-API-docs/blob/updates/SkiaSharpAPI/HarfBuzzSharp/BufferFlags.xml) | :white_check_mark:Succeeded | |
[SkiaSharpAPI/HarfBuzzSharp/Face.xml](https://github.com/mono/SkiaSharp-API-docs/blob/updates/SkiaSharpAPI/HarfBuzzSharp/Face.xml) | :white_check_mark:Succeeded | |
[SkiaSharpAPI/HarfBuzzSharp/Feature.xml](https://github.com/mono/SkiaSharp-API-docs/blob/updates/SkiaSharpAPI/HarfBuzzSharp/Feature.xml) | :white_check_mark:Succeeded | |
[SkiaSharpAPI/HarfBuzzSharp/Flags.xml](https://github.com/mono/SkiaSharp-API-docs/blob/updates/SkiaSharpAPI/HarfBuzzSharp/Flags.xml) | :white_check_mark:Succeeded | |
[SkiaSharpAPI/HarfBuzzSharp/Font.xml](https://github.com/mono/SkiaSharp-API-docs/blob/updates/SkiaSharpAPI/HarfBuzzSharp/Font.xml) | :white_check_mark:Succeeded | |
[SkiaSharpAPI/HarfBuzzSharp/FontExtentsDelegate.xml](https://github.com/mono/SkiaSharp-API-docs/blob/updates/SkiaSharpAPI/HarfBuzzSharp/FontExtentsDelegate.xml) | :white_check_mark:Succeeded | |
[SkiaSharpAPI/HarfBuzzSharp/GlyphAdvanceDelegate.xml](https://github.com/mono/SkiaSharp-API-docs/blob/updates/SkiaSharpAPI/HarfBuzzSharp/GlyphAdvanceDelegate.xml) | :white_check_mark:Succeeded | |
[SkiaSharpAPI/HarfBuzzSharp/Script.xml](https://github.com/mono/SkiaSharp-API-docs/blob/updates/SkiaSharpAPI/HarfBuzzSharp/Script.xml) | :white_check_mark:Succeeded | |
[SkiaSharpAPI/HarfBuzzSharp/Tag.xml](https://github.com/mono/SkiaSharp-API-docs/blob/updates/SkiaSharpAPI/HarfBuzzSharp/Tag.xml) | :white_check_mark:Succeeded | |
[SkiaSharpAPI/SkiaSharp/SKBitmap.xml](https://github.com/mono/SkiaSharp-API-docs/blob/updates/SkiaSharpAPI/SkiaSharp/SKBitmap.xml) | :white_check_mark:Succeeded | |
[SkiaSharpAPI/SkiaSharp/SKData.xml](https://github.com/mono/SkiaSharp-API-docs/blob/updates/SkiaSharpAPI/SkiaSharp/SKData.xml) | :white_check_mark:Succeeded | |
[SkiaSharpAPI/SkiaSharp/SKPixmap.xml](https://github.com/mono/SkiaSharp-API-docs/blob/updates/SkiaSharpAPI/SkiaSharp/SKPixmap.xml) | :white_check_mark:Succeeded | |
[SkiaSharpAPI/index.xml](https://github.com/mono/SkiaSharp-API-docs/blob/updates/SkiaSharpAPI/index.xml) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C6%5C28%5Cd74d06e1-35fd-4f5e-5721-3c1847329f0d%5CPullRequest%5C201906280423186215-11%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=rPMyqGDs%2Bai71mFV6cNojYwhKolLt0VKKJk3ATApO4k%3D&st=2019-06-28T04%3A20%3A19Z&se=2019-07-29T04%3A25%3A19Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by mattleibow** [comment]
Merged into #14

**Pull request closed without merging**
