### PR TITLE
Live

### PR DESCRIPTION
**Pull request by lobrien**

### CODE REVIEW

**Comment by lobrien** [comment]
Docs Build status updates of commit _[e7b51a8](https://github.com/mono/SkiaSharp-API-docs/pull/5/commits/e7b51a86e5a16cefc879af12e4c394363477b3ce)_: 

### :warning: Validation status: warnings


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C5%5C1%5Cd74d06e1-35fd-4f5e-5721-3c1847329f0d%5CPullRequest%5C201905012125578066-5%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=%2B68t6fz3mB9%2FOn6Oz%2Bjju5TCOHxx0joHjdl6SKCA2Q4%3D&st=2019-05-01T21%3A22%3A27Z&se=2019-06-01T21%3A27%3A27Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by lobrien** [comment]
Docs Build status updates of commit _[6d9fbf8](https://github.com/mono/SkiaSharp-API-docs/pull/5/commits/6d9fbf889ea257cbcf32e5bc982dc6221dd025b6)_: 

### :warning: Validation status: warnings


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C5%5C1%5Cd74d06e1-35fd-4f5e-5721-3c1847329f0d%5CPullRequest%5C201905012127138346-5%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=ctxkJAFQeleTHQHGe2bHulDn%2Bf94VcbqpiAAul6e9wg%3D&st=2019-05-01T21%3A23%3A51Z&se=2019-06-01T21%3A28%3A51Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by mattleibow** [comment]
Merged the branches with #8

**Comment by lobrien** [comment]
Docs Build status updates of commit _[c97a845](https://github.com/mono/SkiaSharp-API-docs/pull/5/commits/c97a8451ea9c5847c9fa9f1376eec411622814f0)_: 

### :warning: Validation status: warnings


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C5%5C15%5Cd74d06e1-35fd-4f5e-5721-3c1847329f0d%5CPullRequest%5C201905152045488164-5%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=CzbgeSa%2BQmvPs%2FJGEpVf9eHOvkMVjJnAIF0EIDAmGR4%3D&st=2019-05-15T20%3A42%3A27Z&se=2019-06-15T20%3A47%3A27Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by lobrien** [comment]
Docs Build status updates of commit _[c97a845](https://github.com/mono/SkiaSharp-API-docs/pull/5/commits/c97a8451ea9c5847c9fa9f1376eec411622814f0)_: 

### :warning: Validation status: warnings


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C5%5C15%5Cd74d06e1-35fd-4f5e-5721-3c1847329f0d%5CPullRequest%5C201905152047233203-5%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=GdeazT3P6LoXSJmGgCAiVFATm2tW%2BjkRsGxd%2BpCkRUc%3D&st=2019-05-15T20%3A44%3A25Z&se=2019-06-15T20%3A49%3A25Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
