### PR TITLE
Move to SDP pipeline

### PR DESCRIPTION
**Pull request by TianqiZhang**

### CODE REVIEW

**Comment by conceptdev** [comment]
Docs Build status updates of commit _[64925ab](https://github.com/TianqiZhang/SkiaSharp-API-docs/commits/64925ab20a337bbdd8d0b295e4de7fa9b51ef5a9)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[SkiaSharpAPI/api/SkiaSharp.SKCanvas.DrawText.yml](https://github.com/TianqiZhang/SkiaSharp-API-docs/blob/patch-1/SkiaSharpAPI/api/SkiaSharp.SKCanvas.DrawText.yml) | :warning:Warning | | [Details](#user-content-e951e9e1-fe5b5777)
[SkiaSharpAPI/api/SkiaSharp.Views.Forms.SKGLView.OnTouch.yml](https://github.com/TianqiZhang/SkiaSharp-API-docs/blob/patch-1/SkiaSharpAPI/api/SkiaSharp.Views.Forms.SKGLView.OnTouch.yml) | :warning:Warning | | [Details](#user-content-cc9b8a05-fe5b5777)
[SkiaSharpAPI/api/SkiaSharp.Views.Forms.SKGLView.OnPaintSurface.yml](https://github.com/TianqiZhang/SkiaSharp-API-docs/blob/patch-1/SkiaSharpAPI/api/SkiaSharp.Views.Forms.SKGLView.OnPaintSurface.yml) | :warning:Warning | | [Details](#user-content-0d78ecd2-fe5b5777)
[.openpublishing.publish.config.json](https://github.com/TianqiZhang/SkiaSharp-API-docs/blob/patch-1/.openpublishing.publish.config.json) | :white_check_mark:Succeeded | |

<a id="e951e9e1-fe5b5777"></a>
### [SkiaSharpAPI/api/SkiaSharp.SKCanvas.DrawText.yml](https://github.com/TianqiZhang/SkiaSharp-API-docs/blob/patch-1/SkiaSharpAPI/api/SkiaSharp.SKCanvas.DrawText.yml)
 - **Line 45**: **[Warning]** `````Invalid file link:(~/images/SKCanvasDrawText.png).`````

<a id="cc9b8a05-fe5b5777"></a>
### [SkiaSharpAPI/api/SkiaSharp.Views.Forms.SKGLView.OnTouch.yml](https://github.com/TianqiZhang/SkiaSharp-API-docs/blob/patch-1/SkiaSharpAPI/api/SkiaSharp.Views.Forms.SKGLView.OnTouch.yml)
 - **[Warning]** `````1 invalid cross reference(s) "SkiaSharp.Views.Forms.ISKGLViewController.OnTouch(SkiaSharp.Views.Forms.SKTouchEventArgs)".`````

<a id="0d78ecd2-fe5b5777"></a>
### [SkiaSharpAPI/api/SkiaSharp.Views.Forms.SKGLView.OnPaintSurface.yml](https://github.com/TianqiZhang/SkiaSharp-API-docs/blob/patch-1/SkiaSharpAPI/api/SkiaSharp.Views.Forms.SKGLView.OnPaintSurface.yml)
 - **[Warning]** `````1 invalid cross reference(s) "SkiaSharp.Views.Forms.ISKGLViewController.OnPaintSurface(SkiaSharp.Views.Forms.SKPaintGLSurfaceEventArgs)".`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C10%5C11%5Cd74d06e1-35fd-4f5e-5721-3c1847329f0d%5CPullRequest%5C201910112322564209-16%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=gRp%2BCArSHah69fY%2F7tQC0RkTlFix0UIZA3qqRGZPvfE%3D&st=2019-10-11T23%3A21%3A58Z&se=2019-11-11T23%3A26%3A58Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by conceptdev** [comment]
Docs Build status updates of commit _[ced46b8](https://github.com/TianqiZhang/SkiaSharp-API-docs/commits/ced46b8c75f6f5a4666c5b532436257656636dd7)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[SkiaSharpAPI/api/SkiaSharp.SKCanvas.DrawText.yml](https://github.com/TianqiZhang/SkiaSharp-API-docs/blob/patch-1/SkiaSharpAPI/api/SkiaSharp.SKCanvas.DrawText.yml) | :warning:Warning | | [Details](#user-content-e951e9e1-acf56d58)
[SkiaSharpAPI/api/SkiaSharp.Views.Forms.SKGLView.OnTouch.yml](https://github.com/TianqiZhang/SkiaSharp-API-docs/blob/patch-1/SkiaSharpAPI/api/SkiaSharp.Views.Forms.SKGLView.OnTouch.yml) | :warning:Warning | | [Details](#user-content-cc9b8a05-acf56d58)
[SkiaSharpAPI/api/SkiaSharp.Views.Forms.SKGLView.OnPaintSurface.yml](https://github.com/TianqiZhang/SkiaSharp-API-docs/blob/patch-1/SkiaSharpAPI/api/SkiaSharp.Views.Forms.SKGLView.OnPaintSurface.yml) | :warning:Warning | | [Details](#user-content-0d78ecd2-acf56d58)
[.openpublishing.publish.config.json](https://github.com/TianqiZhang/SkiaSharp-API-docs/blob/patch-1/.openpublishing.publish.config.json) | :white_check_mark:Succeeded | |

<a id="e951e9e1-acf56d58"></a>
### [SkiaSharpAPI/api/SkiaSharp.SKCanvas.DrawText.yml](https://github.com/TianqiZhang/SkiaSharp-API-docs/blob/patch-1/SkiaSharpAPI/api/SkiaSharp.SKCanvas.DrawText.yml)
 - **Line 45**: **[Warning]** `````Invalid file link:(~/images/SKCanvasDrawText.png).`````

<a id="cc9b8a05-acf56d58"></a>
### [SkiaSharpAPI/api/SkiaSharp.Views.Forms.SKGLView.OnTouch.yml](https://github.com/TianqiZhang/SkiaSharp-API-docs/blob/patch-1/SkiaSharpAPI/api/SkiaSharp.Views.Forms.SKGLView.OnTouch.yml)
 - **[Warning]** `````1 invalid cross reference(s) "SkiaSharp.Views.Forms.ISKGLViewController.OnTouch(SkiaSharp.Views.Forms.SKTouchEventArgs)".`````

<a id="0d78ecd2-acf56d58"></a>
### [SkiaSharpAPI/api/SkiaSharp.Views.Forms.SKGLView.OnPaintSurface.yml](https://github.com/TianqiZhang/SkiaSharp-API-docs/blob/patch-1/SkiaSharpAPI/api/SkiaSharp.Views.Forms.SKGLView.OnPaintSurface.yml)
 - **[Warning]** `````1 invalid cross reference(s) "SkiaSharp.Views.Forms.ISKGLViewController.OnPaintSurface(SkiaSharp.Views.Forms.SKPaintGLSurfaceEventArgs)".`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C10%5C16%5Cd74d06e1-35fd-4f5e-5721-3c1847329f0d%5CPullRequest%5C201910160238578940-16%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Hi1EsilJG6C1LMaW7ksAXX%2FYekKePzMp8t5%2FR36ptEs%3D&st=2019-10-16T02%3A38%3A22Z&se=2019-11-16T02%3A43%3A22Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by mimisasouvanh** [comment]
@conceptdev Can you review this PR and merge? Let me know if you have a question.

**Comment by conceptdev** [comment]
Thanks @mimisasouvanh - reviewing with the product owner. Will be merged soon.

**Pull request merged**
